config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change
  # the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it
  # being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                                'static_pages#home'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :categories,          only: [:show]
    resources :products, only: [:show] do
      member do
        get :show_ajax, to: 'products#show_ajax'
      end
      collection do
        get :search, to: 'products#search'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/concerns/potepan/index_resource_actions.rb
module Potepan::IndexResourceActions
  extend ActiveSupport::Concern

  def load_sidebar_resources
    @taxons   = Spree::Taxon.where(depth: 0).includes(:children)
    @colors   = Spree::OptionType.find_by(presentation: "Color").option_values
    @sizes    = Spree::OptionType.find_by(presentation: "Size").option_values
    @taxon_id = params[:taxon_id] || 1
  end

  def load_variants_on_option
    if params[:option_id]
      option_id = params[:option_id]
      sort_type = params[:sort_type] || "new_to_old"
      @selected_variants = Spree::Variant.
        on_products_with_option_id(@products, option_id).
        with_price_and_images.
        order_by(sort_type)
    end
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  MAX_NUMBER_OF_DISPLAY_PRODUCTS = 9
  include Potepan::IndexResourceActions
  before_action :load_products, only: :show
  before_action :load_variants_on_option, only: :show
  before_action :load_sidebar_resources, only: :show

  def show
    if params[:page_type] == "List"
      @page_type = "List"
    else
      # default
      @page_type = "Grid"
    end
    respond_to do |format|
      format.html do
        render 'show'
      end
      format.js
    end
  end

  private

  def load_products
    @selected_taxon = Spree::Taxon.find(params[:id])
    sort_type = params[:sort_type] || "new_to_old"
    @products = Spree::Product.
      on_taxon(@selected_taxon).
      with_price_and_images.
      order_by(sort_type)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_NUMBER_OF_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.friendly.find(params[:id])
    @variant = @product.variants.first || @product.master
    @line_item = Spree::LineItem.new
    @related_products = @product.related_products.
      includes(master: [:default_price, :images]).
      limit(MAX_NUMBER_OF_RELATED_PRODUCTS)

    if params[:taxon_id]
      @taxon = Spree::Taxon.find(params[:taxon_id])
    else
      @taxon = Spree::Taxon.first
    end
  end

  def show_ajax
    @product = Spree::Product.friendly.find(params[:id])
    @variant = @product.variants.find(params[:variant_id])
    @line_item = Spree::LineItem.new
  end

  def search
    @keywords = params[:keywords]

    if @keywords.blank?
      @products = []
    else
      @products = Spree::Product.
        where("spree_products.name LIKE :keyword",
              keyword: "%#{ActiveRecord::Base.sanitize_sql_like(@keywords)}%").
        or(Spree::Product.
          where("spree_products.description LIKE :keyword",
                keyword: "%#{ActiveRecord::Base.sanitize_sql_like(@keywords)}%")).
        includes(master: [:default_price, :images])
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/static_pages_controller.rb
class Potepan::StaticPagesController < ApplicationController
  MAX_NUMBER_OF_NEW_RELEASED_PRODUCTS = 8

  def home
    @new_products = Spree::Product.
      released.
      includes(master: [:default_price, :images]).
      recent(MAX_NUMBER_OF_NEW_RELEASED_PRODUCTS)
  end
end

app/views/potepan/products/_carousel.html.erb
<div id="carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% product.master.images.each_with_index do |image, index| %>
      <div class="<%= index.zero? ? "item active" : "item" %>" data-thumb="<%= index %>">
        <%= image_tag image.attachment(:large) %>
      </div>
    <% end %>
    <% if product.variants.any? %>
      <%= render 'variants_carousel', variant: variant %>
    <% end %>
  </div>
</div>

app/views/potepan/products/_item_images.html.erb
<%= render 'carousel', product: product, variant: variant %>
<%= render 'thumbcarousel', product: product, variant: variant %>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox related_product">
    <div class="productImage clearfix">
      <%= link_to potepan_product_path(product) do %>
        <%= image_tag product.images.first.attachment(:product), alt: product.name %>
      <% end %>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product) do %>
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/_select_option.html.erb
<% if product.variants.any? %>
  <%= form_with url: show_ajax_potepan_product_path, method: :get, html: {style: "display: inline"} do |f| %>
    <span class="quick-drop">
      <%= f.select(:variant_id, '', {}, class: "select-drop", id: "select_variants_option") do %>
        <% product.variants.each do |variant| %>
          <%= content_tag(:option, variant.options_text, value: variant.id) %>
        <% end %>
      <% end %>
    </span>
  <% end %>
<% end %>

app/views/potepan/products/_select_quantity_and_cart_button.html.erb
<% if  variant.stock_items.where(backorderable: true).any? %>
  <%= form_with model: line_item, url: "#", method: :get, html: {style: "display: inline"} do |f| %>
    <%= f.hidden_field(:variant_id, value: variant.id) %>
    <span class="quick-drop resizeWidth" >
      <%= f.select(:quantity, (1..10).to_a, {}, class: "select-drop") %>
    </span>
    <div class="btn-area">
      <%= button_tag :type => "submit", :class =>"btn btn-primary btn-block" do %>
        カートへ入れる<i class="fa fa-angle-right"　aria-hidden="true"></i>
      <% end %>
    </div>
  <% end %>
<% elsif variant.total_on_hand.zero? %>
  <span class="quick-drop resizeWidth">
    <select class= "select-drop">
      <option value="0">0</option>
    </select>
  </span>
  <div class="btn-area">
    <button disabled class="btn btn-primary btn-block">
      在庫なし<i class="fa fa-angle-right"　aria-hidden="true"></i>
    </button>
  </div>
<% else %>
  <%= form_with model: line_item, url: "#", method: :get, html: {style: "display: inline"} do |f| %>
    <%= f.hidden_field(:variant_id, value: variant.id) %>
    <span class="quick-drop resizeWidth" >
      <%= f.select(:quantity, (1..variant.total_on_hand).to_a, {}, class: "select-drop") %>
    </span>
    <div class="btn-area">
      <%= button_tag :type => "submit", :class =>"btn btn-primary btn-block" do %>
        カートへ入れる<i class="fa fa-angle-right"　aria-hidden="true"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/potepan/products/_thumbcarousel.html.erb
<div class="clearfix">
  <div id="thumbcarousel" class="carousel slide" data-interval="false">
    <div class="carousel-inner">
      <% product.master.images.each_with_index do |image, index| %>
        <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
          <%= image_tag image.attachment(:small) %>
        </div>
      <% end %>
      <% if product.variants.any? %>
        <%= render 'variants_thumbcarousel', variant: variant %>
      <% end %>
    </div>
    <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

app/views/potepan/products/_variants_carousel.html.erb
<% variant.images.each.with_index(variant.images.count) do |image, index| %>
  <div class="item" data-thumb="<%= index %>">
    <%= image_tag image.attachment(:large) %>
  </div>
<% end %>

app/views/potepan/products/_variants_thumbcarousel.html.erb
<% variant.images.each.with_index(variant.images.count) do |image, index| %>
  <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
    <%= image_tag image.attachment(:small) %>
  </div>
<% end %>

app/views/potepan/products/search.html.erb
<% provide(:title, "result by search #{@keywords}") %>
<section class="lightSection clearfix pageHeader">
  <%= render 'shared/light_section_page_header', page_title: @keywords, page_address: "search/#{@keywords}" %>
</section>
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render partial: 'potepan/spree/products/product_for_search', collection: @products, as: :product %>
      <% if @products.empty? %>
        <h2 class="text-center">No results</h2>
      <% end %>
    </div>
  </div>
</section>

app/views/potepan/products/search_result.html.erb
<% provide(:title, "Search Result") %>
<section class="lightSection clearfix pageHeader">
  <%= render 'shared/light_section_page_header', page_title: "Search Result with #{@keyword}", page_address: "Keyword Search" %>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar" id="sidebar">
        <%= render 'shared/left_sidebar', taxons: @taxons, colors: @colors, sizes: @sizes, selected_taxon: @selected_taxon %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= render 'shared/sort_dropdown_list' %>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right view-switch-button" role="group">
              <%= render 'shared/grid_list_switch_button', selected_taxon: @selected_taxon, active_type: @page_type %>
            </div>
          </div>
        </div>
        <div class="row products productListSingle">
          <% if @products.empty? %>
            <div class="alert alert-warning">No products found</div>
          <% elsif @selected_variants %>
            <%= render @selected_variants, selected_taxon: @selected_taxon, page_type: @page_type %>
          <% else %>
            <%= render @products, selected_taxon: @selected_taxon, page_type: @page_type %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'shared/light_section_partners_logo' %>

app/views/potepan/products/show.html.erb
<% provide(:title, "#{@product.name}") %>
<section class="lightSection clearfix pageHeader">
  <%= render 'shared/light_section_page_header', page_title: @product.name, page_address: @product.name %>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider" id="item_images">
            <%= render 'item_images', product: @product, variant: @variant %>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(@taxon.id) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <p><%= @product.description %></p>
            <h3 id="item_price"><%= @variant.display_price %></h3>
            <%= render 'select_option', product: @product, variant: @variant %>
            <div id="select_quantity_and_cart_button" style= "display: inline">
              <%= render 'select_quantity_and_cart_button', variant: @variant, line_item: @line_item %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <%= render partial: "related_product", collection: @related_products, as: :product %>
    </div>
  </div>
</section>

app/views/potepan/products/show_ajax.js.erb
$("#item_images").html("<%= escape_javascript(render 'item_images', product: @product, variant: @variant) %>");
$("#item_price").html('<%= @variant.display_price %>');
$("#select_quantity_and_cart_button").html("<%= escape_javascript(render 'select_quantity_and_cart_button', variant: @variant, line_item: @line_item) %>");